ProxyPreserveHost On
ProxyPass /bill-api/ http://127.0.0.1:3001/
ProxyPassReverse /bill-api/ http://127.0.0.1:3001/

RedirectMatch 301 ^/bill$ /bill/
Alias /bill/ /var/www/bills/frontend/dist/
<Directory "/var/www/bills/frontend/dist">
    Options -Indexes
    AllowOverride None
    Require all granted

    DirectoryIndex index.html
    FallbackResource /bill/index.html
</Directory>
