ALTER TABLE "budgets" ADD COLUMN "rel215" REAL NOT NULL DEFAULT 0;
ALTER TABLE "budgets" ADD COLUMN "rel224" REAL NOT NULL DEFAULT 0;
ALTER TABLE "budgets" ADD COLUMN "rel233" REAL NOT NULL DEFAULT 0;
