import { createContext, useContext } from 'react';

export type Language = 'en' | 'mr';
export type Theme = 'light' | 'dark';

type AppSettings = {
  language: Language;
  t: (text: string) => string;
};

const translations: Record<string, string> = {
  'Financial workspaces': 'आर्थिक कार्यक्षेत्रे',
  'Stage': 'टप्पा',
  'On hold': 'प्रलंबित',
  'Invoice Raised': 'चलन नोंदवले',
  'PMC Check': 'PMC तपासणी',
  'TFC/TEC Committee Approval': 'TFC/TEC समिती मंजुरी',
  'Put Up on File': 'फाईलवर सादर',
  'Sent to Treasury': 'कोषागाराकडे पाठवले',
  'Cleared by Treasury': 'कोषागार मंजुरी',
  'Object head': 'वस्तू शीर्ष',
  'Total': 'एकूण',
  'Amount released (₹)': 'वितरित रक्कम (₹)',
  'Bills pipeline': 'बिल प्रक्रिया',
  'Clearance, exceptions & register': 'मंजुरी, अपवाद आणि नोंदवही',
  'Budget by FY': 'आर्थिक वर्षानुसार अंदाजपत्रक',
  'Provisions, expenditure & balance': 'तरतूद, खर्च आणि शिल्लक',
  'Fund transfers': 'निधी हस्तांतरण',
  'Recipients, utilization & districts': 'प्राप्तकर्ते, वापर आणि जिल्हे',
  'Bill & Budget Tracker': 'बिल आणि अंदाजपत्रक ट्रॅकर',
  'MahaSTRIDE financial operations workspace': 'महाSTRIDE आर्थिक कार्यक्षेत्र',
  'live': 'थेट',
  'Appearance': 'दिसण्याची पद्धत',
  'Total bill value': 'बिलांची एकूण रक्कम',
  'Cleared by treasury': 'कोषागाराकडून मंजूर',
  'In pipeline': 'प्रक्रियेत',
  'Approved, mid-pipeline': 'मधल्या टप्प्यात मंजूर',
  'Oldest open bill': 'सर्वात जुने खुले बिल',
  'needs attention': 'लक्ष देणे आवश्यक',
  'on hold': 'प्रलंबित',
  'Invoice': 'चलन',
  'By DSU / vendor': 'DSU / विक्रेत्यानुसार',
  '₹ value, split by clearance status': '₹ रक्कम, मंजुरी स्थितीनुसार',
  'On hold — needs action': 'प्रलंबित — कृती आवश्यक',
  'TFC / TEC approval': 'TFC / TEC मंजुरी',
  'TFC / TEC (Bill) committee approval': 'TFC / TEC (बिल) समिती मंजुरी',
  'Raising of invoice': 'चलन नोंदणी',
  'Check by PMC': 'PMC कडून तपासणी',
  'Putting it up on file': 'फाईलवर सादर',
  'Sent to treasury': 'कोषागाराकडे पाठवले',
  'Clearance by treasury': 'कोषागार मंजुरी',
  'Invoice raised': 'चलन नोंदवले',
  'PMC check': 'PMC तपासणी',
  'Put up on file': 'फाईलवर सादर',
  'Treasury clearance': 'कोषागार मंजुरी',
  'STAGE': 'टप्पा',
  'bill': 'बिल',
  'bills': 'बिले',
  'No bill activity yet': 'अद्याप बिल व्यवहार नाही',
  'Vendor summaries will appear here when bills are entered.': 'बिले नोंदवल्यावर विक्रेता सारांश येथे दिसेल.',
  'On-hold bills will be listed here.': 'प्रलंबित बिले येथे दिसतील.',
  'Nothing needs attention': 'लक्ष देण्यासारखे काही नाही',
  'No pending bills to age.': 'वय मोजण्यासाठी प्रलंबित बिले नाहीत.',
  'Status / tracker remark': 'स्थिती / नोंद',
  'E-file number': 'ई-फाईल क्रमांक',
  'E-file no.': 'ई-फाईल क्र.',
  'Program / District': 'कार्यक्रम / जिल्हा',
  'Stage history': 'टप्प्यांचा इतिहास',
  'Bill audit trail': 'बिल कार्यवाही इतिहास',
  'Chronological record of this bill’s workflow stages.': 'या बिलाच्या प्रक्रिया टप्प्यांची कालानुक्रमिक नोंद.',
  'Bill details': 'बिल तपशील',
  'Current stage': 'सध्याचा टप्पा',
  'Workflow timeline': 'प्रक्रिया कालरेषा',
  'Oldest event first': 'जुनी नोंद प्रथम',
  'Current': 'सध्याचा',
  'Imported snapshot': 'आयात केलेला स्नॅपशॉट',
  'Initial record': 'प्रारंभिक नोंद',
  'Workflow update': 'प्रक्रिया अद्यतन',
  'Bill created': 'बिल तयार केले',
  'This is the recorded workflow history; snapshot entries do not include unavailable earlier stages.': 'ही नोंदवलेली प्रक्रिया आहे; स्नॅपशॉटमध्ये उपलब्ध नसलेले मागील टप्पे समाविष्ट नाहीत.',
  'Bill actions': 'बिल कृती',
  'Only the current stage was available when history tracking began.': 'इतिहास नोंद सुरू झाली तेव्हा फक्त सध्याचा टप्पा उपलब्ध होता.',
  'Snapshot; earlier stages unavailable': 'स्नॅपशॉट; पूर्वीचे टप्पे उपलब्ध नाहीत',
  'Filtered total': 'फिल्टर केलेली एकूण रक्कम',
  '"#" renumbers with your current filter/sort · click Date / Amount to sort · click ✎ to edit': 'सध्याच्या फिल्टर/क्रमवारीनुसार क्रमांक बदलतात · दिनांक / रक्कम निवडून क्रमवारी लावा · ✎ निवडून संपादन करा',
  'Edit bill': 'बिल संपादित करा',
  'Vendor / DSU': 'विक्रेता / DSU',
  'Invoice date': 'चलन दिनांक',
  'Budget code': 'अंदाजपत्रक संकेतांक',
  'Select budget code': 'अंदाजपत्रक संकेतांक निवडा',
  'Object Head': 'वस्तू शीर्ष',
  'Select Object Head': 'वस्तू शीर्ष निवडा',
  'TFC / TEC Committee Approval': 'TFC / TEC समिती मंजुरी',
  'Linked transfer (used when cleared)': 'जोडलेले हस्तांतरण (मंजुरीनंतर वापरले जाते)',
  'No linked transfer': 'जोडलेले हस्तांतरण नाही',
  'Save bill': 'बिल जतन करा',
  'Total approved budget': 'एकूण मंजूर अंदाजपत्रक',
  'Total expenditure to date': 'आजपर्यंतचा एकूण खर्च',
  'Balance remaining': 'उर्वरित शिल्लक',
  'Approved budget vs. expenditure — object code wise': 'मंजूर अंदाजपत्रक विरुद्ध खर्च — वस्तू संकेतांकानुसार',
  'Cross-check against bill register': 'बिल नोंदवहीशी पडताळणी',
  '3451A215 = PMU establishment · A224 = IPF (World Bank) · A233 = PforR (state share) — per the GoM Budget Head Creation GRs': '3451A215 = PMU स्थापना · A224 = IPF (जागतिक बँक) · A233 = PforR (राज्य हिस्सा) — GoM बजेट शीर्ष निर्मिती शासन निर्णयानुसार',
  'only bills cleared': 'फक्त मंजूर बिले',
  'in': 'मध्ये',
  "count toward this year's expenditure": 'या वर्षाच्या खर्चात मोजली जातात',
  'Totals combine provisions, expenditures, and cleared bills across all fiscal years': 'एकूण रकमेत सर्व आर्थिक वर्षांतील तरतुदी, खर्च आणि मंजूर बिले समाविष्ट आहेत',
  'Total transferred': 'एकूण हस्तांतरित',
  'Unutilized balance': 'वापराविना शिल्लक',
  'Awaiting minutes': 'इतिवृत्त प्रतीक्षेत',
  'releases': 'वितरणे',
  'awaiting UC': 'उपयोगिता प्रमाणपत्र प्रतीक्षेत',
  'not yet released': 'अद्याप वितरित नाही',
  'all released': 'सर्व वितरित',
  'record': 'नोंद',
  'records': 'नोंदी',
  'Collapse': 'आकुंचित करा',
  'Expand': 'विस्तारित करा',
  'Summary view': 'सारांश दृश्य',
  'Detail view': 'तपशील दृश्य',
  '4 detail columns': '४ तपशील स्तंभ',
  'Budget column groups': 'अंदाजपत्रक स्तंभ गट',
  'Use a funding-head control to switch between its four detail columns and a utilization summary. Utilization is expenditure divided by release.': 'चार तपशील स्तंभ आणि वापर सारांश यांमध्ये बदलण्यासाठी निधी-शीर्ष नियंत्रण वापरा. वापर म्हणजे वितरित रकमेच्या तुलनेत झालेला खर्च.',
  'Utilization': 'वापर',
  'A215 utilization': 'A215 वापर',
  'A224 utilization': 'A224 वापर',
  'A233 utilization': 'A233 वापर',
  'Total utilization': 'एकूण वापर',
  'released': 'वितरित',
  'No release': 'वितरण नाही',
  'No release recorded': 'वितरण नोंदलेले नाही',
  'Over release': 'वितरणापेक्षा अधिक खर्च',
  'Release': 'वितरण',
  'Total release': 'एकूण वितरण',
  'A215 Release': 'A215 वितरण',
  'A224 Release': 'A224 वितरण',
  'A233 Release': 'A233 वितरण',
  'transfers for': 'यांची हस्तांतरणे',
  'transfer': 'हस्तांतरण',
  'transfers': 'हस्तांतरणे',
  'total': 'एकूण',
  'Unassigned': 'नियुक्त नाही',
  'Utilized amount for': 'वापरलेली रक्कम:',
  'Total released': 'एकूण वितरित',
  'Awaiting release': 'वितरण प्रतीक्षेत',
  'Design brackets': 'अनुदान श्रेणी',
  'across 6 divisions': '६ विभागांमध्ये',
  'no amount entered yet': 'अद्याप रक्कम नोंदलेली नाही',
  'per qualifying district': 'पात्र जिल्ह्यानुसार',
  'Object code': 'वस्तू संकेतांक',
  'Amount transferred (₹)': 'हस्तांतरित रक्कम (₹)',
  'e.g. District Collector, Nashik': 'उदा. जिल्हाधिकारी, नाशिक',
  'e.g. Contractual Services': 'उदा. कंत्राटी सेवा',
  'Amount released for': 'वितरित रक्कम:',
  'Remarks for': 'शेरा:',
  'A project by SaJo & XHiman': 'SaJo आणि XHiman यांचा प्रकल्प',
  'Made by XHiman': 'XHiman निर्मित',
  'Bill stage is inferred from the status entry; changing the status recomputes its pipeline stage. FY 2026-27 provisions originate from the STATUS workbook EXPEND sheet (6 Aug 2026); other fiscal years are populated from imported figures. Transferred amounts and cleared bills update budget expenditure, while bills linked to a transfer update its utilization without double-counting. Clearance FY is read from the clearance date in the status text. District release fields can be filled as approvals are recorded.': 'बिलाचा टप्पा स्थितीच्या नोंदीवरून ठरवला जातो; स्थिती बदलल्यास बिल प्रक्रिया टप्पा पुन्हा मोजला जातो. आर्थिक वर्ष २०२६-२७ ची तरतूद STATUS कार्यपुस्तिकेतील EXPEND पत्रकातून (६ ऑगस्ट २०२६) घेतली आहे; इतर वर्षांची माहिती आयात केलेल्या आकड्यांवरून भरली जाते. हस्तांतरित रक्कम आणि मंजूर बिले अंदाजपत्रक खर्च अद्ययावत करतात; हस्तांतरणाशी जोडलेली बिले दुहेरी मोजणी न करता वापर अद्ययावत करतात. मंजुरीचे आर्थिक वर्ष स्थितीतील मंजुरी दिनांकावरून घेतले जाते. मंजुरी मिळाल्यावर जिल्हा वितरण तपशील भरता येतात.',
  'Cleared across fiscal years': 'सर्व आर्थिक वर्षांत मंजूर',
  'Cleared in': 'मंजूर',
  'from register': 'नोंदवहीतून',
  'vs. EXPEND-sheet expenditure': 'EXPEND पत्रकातील खर्चाशी तुलना',
  'from the object-code table above': 'वरील वस्तू संकेतांक तक्त्यातून',
  'Cleared in other FYs (excluded)': 'इतर आर्थिक वर्षांत मंजूर (वगळलेले)',
  'none so far': 'आतापर्यंत काहीही नाही',
  'Not yet cleared': 'अद्याप मंजूर नाही',
  'still in the pipeline': 'अजून प्रक्रियेत',
  '₹8 Cr / ₹12 Cr / ₹16 Cr brackets per qualifying district · per the Incentive GR dated 15 Apr 2026': 'पात्र जिल्ह्यानुसार ₹८ कोटी / ₹१२ कोटी / ₹१६ कोटी श्रेणी · १५ एप्रिल २०२६ च्या प्रोत्साहन शासन निर्णयानुसार',
  'All 36 districts listed by division; fund design (brackets only) is finalized but district-wise qualification scoring and disbursement are not yet in any source record — fill in as SSC/Finance Dept. approves releases.': 'विभागनिहाय सर्व ३६ जिल्हे सूचीबद्ध आहेत; निधी रचना (फक्त श्रेणी) निश्चित आहे, परंतु जिल्हानिहाय पात्रता गुणांकन आणि वितरणाची नोंद स्रोतांमध्ये नाही — SSC/वित्त विभागाची मंजुरी मिळताच तपशील भरा.',
  'Click a cell to edit': 'संपादनासाठी सेल निवडा',
  'IPF 70 % Bank Share': 'IPF ७०% बँक हिस्सा',
  'IPF 30% State Share': 'IPF ३०% राज्य हिस्सा',
  '70% PforR - Bank Share': '७०% PforR - बँक हिस्सा',
  'Salary': 'वेतन',
  'Telephone/Electricity/Water': 'दूरध्वनी/वीज/पाणी',
  'Contractual Services': 'कंत्राटी सेवा',
  'Domestic Travel': 'देशांतर्गत प्रवास',
  'Office Expenses': 'कार्यालयीन खर्च',
  'Rent and Taxes': 'भाडे आणि कर',
  'Publications': 'प्रकाशने',
  'Computer Expenses': 'संगणक खर्च',
  'Supplies and Materials': 'पुरवठा आणि साहित्य',
  'Petrol/Oil/Lubricant': 'पेट्रोल/तेल/वंगण',
  'Advertisement and Publicity': 'जाहिरात आणि प्रसिद्धी',
  'Minor Works': 'किरकोळ कामे',
  'Professional Services': 'व्यावसायिक सेवा',
  'Grant-in-aid (non-salary)': 'सहाय्यक अनुदान (वेतनाव्यतिरिक्त)',
  'of': 'पैकी',
  'stages': 'टप्पे',
  'Failed to save bill. Check the browser console.': 'बिल जतन करता आले नाही. ब्राउझर कन्सोल तपासा.',
  'utilized': 'वापरलेले',
  'spent': 'खर्च',
  'of budget': 'अंदाजपत्रकापैकी',
  'of transferred': 'हस्तांतरित रकमेतून',
  'district': 'जिल्हा',
  'districts': 'जिल्हे',
  'recorded': 'नोंदले',
  'Switch to dark mode': 'डार्क मोड सुरू करा',
  'Switch to light mode': 'लाईट मोड सुरू करा',
  'Dark': 'डार्क',
  'Light': 'लाईट',
  'Language': 'भाषा',
  'English': 'English',
  'मराठी': 'मराठी',
  'How figures and bill statuses are calculated': 'आकडे आणि बिल स्थिती कशी मोजली जाते',
  'Bill clearance process': 'बिल मंजुरी प्रक्रिया',
  'six checkpoints tracked below, in order': 'खाली सहा टप्प्यांचा मागोवा घेतला आहे',
  'Bills by pipeline stage': 'प्रक्रियेच्या टप्प्यानुसार बिले',
  'value currently sitting at each checkpoint (not cumulative)': 'प्रत्येक टप्प्यावर सध्या असलेली रक्कम (एकत्रित नाही)',
  'Full bill register': 'संपूर्ण बिल नोंदवही',
  'Export CSV': 'CSV निर्यात',
  'Add bill': 'बिल जोडा',
  'No bills have been added yet. Use “Add bill” to start the register.': 'अद्याप कोणतीही बिले जोडलेली नाहीत. नोंदवही सुरू करण्यासाठी “बिल जोडा” निवडा.',
  'No bills match the selected search or filters.': 'निवडलेल्या शोध किंवा फिल्टरशी कोणतेही बिल जुळत नाही.',
  'Search vendor, invoice no. or status…': 'विक्रेता, चलन क्रमांक किंवा स्थिती शोधा…',
  'Search vendor, invoice no., E-file or status…': 'विक्रेता, चलन क्रमांक, ई-फाईल किंवा स्थिती शोधा…',
  'All stages': 'सर्व टप्पे',
  'All statuses': 'सर्व स्थिती',
  'Vendor': 'विक्रेता',
  'Invoice no.': 'चलन क्र.',
  'Date': 'दिनांक',
  'Amount': 'रक्कम',
  'Cleared FY': 'मंजुरीचे आर्थिक वर्ष',
  'Payment attribute': 'देयक तपशील',
  'Cleared': 'मंजूर',
  'In progress': 'प्रगतीत',
  'On hold / exception': 'प्रलंबित / अपवाद',
  'Oldest pending bills': 'सर्वात जुनी प्रलंबित बिले',
  'days since invoice raised, still uncleared': 'चलन नोंदवल्यापासूनचे दिवस; अद्याप मंजुरी नाही',
  'Days pending': 'प्रलंबित दिवस',
  'Current status': 'सध्याची स्थिती',
  'Undo': 'पूर्ववत',
  'Saving…': 'जतन होत आहे…',
  'Save': 'जतन करा',
  'Code': 'संकेतांक',
  'Provision': 'तरतूद',
  'Expenditure': 'खर्च',
  'Balance': 'शिल्लक',
  'Total provision': 'एकूण तरतूद',
  'Total expenditure': 'एकूण खर्च',
  'Loading budget data…': 'अंदाजपत्रक माहिती लोड होत आहे…',
  'Fund transfers — agencies / DDOs': 'निधी हस्तांतरण — संस्था / DDO',
  'Recipient': 'प्राप्तकर्ता',
  'Purpose / object code': 'उद्देश / वस्तू संकेतांक',
  'Amount transferred': 'हस्तांतरित रक्कम',
  'Order date': 'आदेश दिनांक',
  'Release status': 'वितरण स्थिती',
  'Utilized to date': 'आजपर्यंत वापरलेली रक्कम',
  'Remarks': 'शेरा',
  'No transfers recorded': 'हस्तांतरण नोंदलेले नाही',
  'Record a release to start tracking recipients, utilization, and remaining balances.': 'प्राप्तकर्ते, वापर आणि उर्वरित शिल्लक यांचा मागोवा सुरू करण्यासाठी वितरण नोंदवा.',
  'Add transfer': 'हस्तांतरण जोडा',
  'Transferred': 'हस्तांतरित',
  'Minutes awaited': 'इतिवृत्त प्रतीक्षेत',
  'Edit': 'संपादन',
  'Each row is one transfer. Linked cleared bills update that transfer’s utilized total; its amount is counted against the selected budget year/head when transferred.': 'प्रत्येक ओळ एक हस्तांतरण दर्शवते. जोडलेली मंजूर बिले वापरलेली एकूण रक्कम अद्ययावत करतात; हस्तांतरणाच्या वेळी निवडलेल्या आर्थिक वर्ष/शीर्षात रक्कम मोजली जाते.',
  'Click "Utilized" to edit': 'संपादनासाठी “वापरलेली रक्कम” निवडा',
  'District Incentive Fund — DLI-1 performance grants': 'जिल्हा प्रोत्साहन निधी — DLI-1 कामगिरी अनुदान',
  'Districts': 'जिल्हे',
  'Division': 'विभाग',
  'Amount released': 'वितरित रक्कम',
  'Release date': 'वितरण दिनांक',
  'Add district': 'जिल्हा जोडा',
  'Add district record': 'जिल्हा नोंद जोडा',
  'Cancel': 'रद्द करा',
  'Save changes': 'बदल जतन करा',
  'Save transfer': 'हस्तांतरण जतन करा',
  'Save district': 'जिल्हा जतन करा',
  'Purpose': 'उद्देश',
  'Budget funding head': 'अंदाजपत्रक निधी शीर्ष',
  'Fiscal year': 'आर्थिक वर्ष',
  'Amount (₹)': 'रक्कम (₹)',
  'Utilized to date (₹)': 'आजपर्यंत वापरलेली रक्कम (₹)',
  'District': 'जिल्हा',
  'Enter both recipient and purpose.': 'प्राप्तकर्ता आणि उद्देश दोन्ही नोंदवा.',
  'Enter the transfer date for a transferred amount.': 'हस्तांतरित रकमेसाठी हस्तांतरण दिनांक नोंदवा.',
  'Enter both a district and division.': 'जिल्हा आणि विभाग दोन्ही नोंदवा.',
};

export const AppSettingsContext = createContext<AppSettings>({
  language: 'en',
  t: text => text,
});

export function useAppSettings() {
  return useContext(AppSettingsContext);
}

export function translate(text: string, language: Language): string {
  return language === 'mr' ? (translations[text] ?? text) : text;
}
